version: "3.8"
services:
  
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: react-app
    working_dir: /app
    image: react-app
    env_file: .env
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes: 
      - "./app:/app"
      - "./app/node_modules"